services:
  api:
    image: ghcr.io/yufengguan/psvalidator-api:latest
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DocsPath=/app/Docs
    volumes:
      - ./Docs:/app/Docs
    depends_on:
      - seq
    restart: always

  seq:
    image: datalust/seq:2024.3
    container_name: psvalidator-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    restart: unless-stopped
    volumes:
      - ./seq-data:/data

  app:
    image: ghcr.io/yufengguan/psvalidator-app:latest
    build:
      context: ./App
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx-api.conf:/etc/nginx/conf.d/api.conf
      - ./nginx/nginx-stubserver.conf:/etc/nginx/conf.d/stubserver.conf
      - ./nginx/nginx-seq.conf:/etc/nginx/conf.d/seq.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  stubserver:
    image: ghcr.io/yufengguan/psvalidator-stubserver:latest
    build:
      context: .
      dockerfile: Tests/StubServer/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MockResponsePath=Docs/MockXmlResponses
    volumes:
      - ./Docs:/app/Docs
    restart: always
